"""Added Deploy model

Revision ID: bef0c36df757
Revises: 
Create Date: 2018-09-27 10:37:39.189279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef0c36df757'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deploys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deploys')
    # ### end Alembic commands ###
