# Generated by Django 2.1.1 on 2018-09-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_app_repo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='description',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua', max_length=256),
        ),
        migrations.AddField(
            model_name='app',
            name='stack',
            field=models.CharField(default='python', max_length=32),
        ),
        migrations.AddField(
            model_name='app',
            name='status',
            field=models.CharField(default='blank', max_length=64),
        ),
    ]
