# Generated by Django 2.1.1 on 2018-09-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180928_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='commit_hash_abbreviated',
            field=models.CharField(default='0000000', max_length=30),
        ),
    ]
